apikey:

network:
  - polkadot
  - kusama
  - darwinia
  - acala
  - acala-testnet
  - alephzero
  - astar
  - altair
  - bifrost-kusama
  - bifrost
  - calamari
  - centrifuge
  - clover
  - clv
  - clover-testnet
  - composable
  - crust
  - crust-parachain
  - shadow
  - crab
  - dbc
  - dock
  - dolphin
  - integritee
  - interlay
  - karura
  - kintsugi
  - khala
  - kilt-testnet
  - spiritnet
  - moonbase
  - moonbeam
  - moonriver
  - nodle
  - pangolin
  - pangoro
  - parallel
  - parallel-heiko
  - picasso
  - pioneer
  - polkadex
  - polymesh
  - polymesh-testnet
  - quartz
  - rococo
  - sakura
  - shibuya
  - shiden
  - sora
  - stafi
  - turing
  - westend
  - zeitgeist
  - unique
  - subspace
  - manta
  - assethub-polkadot
  - assethub-kusama
  - assethub-rococo
  - krest
  - agung-testnet
  - polkadex-parachain
  - joystream
  - canary-matrix
  - matrix
  - enjin
  - canary
  - tanssi-testnet
  - creditcoin-testnet
  - creditcoin
