apikey:

network:
  - polkadot
  - kusama
  - darwinia
  - acala
  - acala-testnet
  - alephzero
  - astar
  - altair
  - bifrost
  - calamari
  - centrifuge
  - chainx
  - clover
  - clv
  - clover-testnet
  - composable
  - crab-parachain
  - crust
  - maxwell
  - shadow
  - dali
  - crab
  - dbc
  - dock
  - dolphin
  - edgeware
  - encointer
  - equilibrium
  - integritee
  - interlay
  - karura
  - kintsugi
  - kulupu
  - khala
  - kilt-testnet
  - spiritnet
  - litmus
  - moonbase
  - moonbeam
  - moonriver
  - nodle
  - pangolin
  - pangolin-parachain
  - pangoro
  - parallel
  - parallel-heiko
  - picasso
  - pioneer
  - polkadex
  - polymesh
  - polymesh-testnet
  - quartz
  - reef
  - rococo
  - sakura
  - shibuya
  - shiden
  - sora
  - subgame
  - stafi
  - statemine
  - statemint
  - turing
  - uniarts
  - westend
  - zeitgeist

param_rule:
  - domain: polkadot
    wsAddr: wss://rpc.polkadot.io/
    pallet:
      - name: Balances
        event:
          - name: Transfer
            param: [ AccountId,AccountId,Balance ]
        extrinsic:
          - name: Transfer
            param: [ Address, Balance ]
  - domain: khala
    wsAddr: xx
    pallet:
      - name: Balances
        event:
          - name: Transfer
            param: [ AccountId,AccountId,Balance ]
      - name: System
        event:
          - name: ExtrinsicSuccess
            param: [ DispatchInfo ]
          - name: ExtrinsicFailed
            param: [ DispatchError,DispatchInfo ]
  - domain: zeitgeist
    wsAddr:
    rule_inherit: polkadot