apikey:

network:
  - polkadot
  - kusama
  - darwinia
  - acala
  - acala-testnet
  - alephzero
  - astar
  - altair
  - bifrost-kusama
  - bifrost
  - calamari
  - centrifuge
  - clover
  - clv
  - clover-testnet
  - composable
  - crust
  - crust-parachain
  - shadow
  - crab
  - dbc
  - dock
  - dolphin
  - edgeware
  - encointer
  - equilibrium
  - integritee
  - interlay
  - karura
  - kintsugi
  - khala
  - kilt-testnet
  - spiritnet
  - moonbase
  - moonbeam
  - moonriver
  - nodle
  - pangolin
  - pangoro
  - parallel
  - parallel-heiko
  - picasso
  - pioneer
  - polkadex
  - polymesh
  - polymesh-testnet
  - quartz
  - reef
  - rococo
  - sakura
  - shibuya
  - shiden
  - sora
  - subgame
  - stafi
  - statemine
  - statemint
  - turing
  - uniarts
  - westend
  - zeitgeist
  - unique
  - datahighway
  - subspace
