apikey:

network:
  - polkadot
  - kusama
  - moonbeam
  - moonriver
  - phala
  - crab
  - crust
  - darwinia
  - centrifuge
  - stafi
  - dock
  - dock-poa
  - dbc
  - karura
  - westend
  - moonbase
  - clover
  - clover-testnet
  - kilt-testnet
  - sora
  - khala
  - crust-parachain
  - bifrost
  - shiden
  - shibuya
  - sakura
  - robonomics
  - spiritnet
  - calamari
  - polymesh-testnet
  - polymesh
  - polkadex
  - integritee
  - parallel-heiko
  - dolphin
  - acala-testnet
  - astar
  - acala
  - parallel
  - clv
  - quartz
  - kintsugi
  - shadow
  - alephzero
  - altair
  - picasso
  - rococo
  - pioneer
  - centrifuge-parachain
  - nodle
  - interlay
  - zeitgeist
  - mangatax
  - dali
  - composable
  - turing
  - bifrost-kusama
  - efinity
  - unique
  - basilisk
  - hydradx
  - datahighway
  - equilibrium-beta
  - subspace
  - origintrail-testnet
  - origintrail
  - bajun
  - pangolin
  - humanode
  - manta
  - picasso-rococo
  - centrifuge-standalone-history
  - efinity-parachain-archive
  - vara
  - rockmine
  - statemine
  - statemint
  - assethub-polkadot
  - assethub-kusama
  - assethub-rococo
  - krest
  - agung-testnet
  - polkadex-parachain
  - joystream
  - canary-matrix
  - matrix
  - enjin
  - canary
  - dancebox
  - creditcoin-testnet
  - creditcoin
