name: CI

permissions:
  contents: read

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - conf/**.yaml
      - '**.md'
  push:
    paths-ignore:
      - conf/**.yaml
      - '**.md'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m